

/** */
function getAlbums(req, res) {
  res.status(200).send([
    {
      href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5/albums?offset=0&limit=20&include_groups=album,single,compilation,appears_on",
      items: [
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/43otFXrY0bgaq5fB3GrZj6"
          },
          href: "https://api.spotify.com/v1/albums/43otFXrY0bgaq5fB3GrZj6",
          id: "43otFXrY0bgaq5fB3GrZj6",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/8deed63f89e0a215e90de1ee5809780921a47747",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/1873c24573305cb945ed9650cac7538a21cd1a8c",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/560af78cea7816e2f73d7abee550093741e975be",
              width: 64
            }
          ],
          name: "The Getaway",
          release_date: "2016-06-17",
          release_date_precision: "day",
          total_tracks: 13,
          type: "album",
          uri: "spotify:album:43otFXrY0bgaq5fB3GrZj6"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/5wZtSIvijWCMc1vlPFqAyB"
          },
          href: "https://api.spotify.com/v1/albums/5wZtSIvijWCMc1vlPFqAyB",
          id: "5wZtSIvijWCMc1vlPFqAyB",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/66ab66e38e40a9202e8417a0b59ad86a210637a7",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/b5f95aec74da0bc27397aad2daf161571deb1ffc",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/02ffe96d555f36ba45daae369787d45112842f7b",
              width: 64
            }
          ],
          name: "I'm With You",
          release_date: "2011-08-29",
          release_date_precision: "day",
          total_tracks: 14,
          type: "album",
          uri: "spotify:album:5wZtSIvijWCMc1vlPFqAyB"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/7xl50xr9NDkd3i2kBbzsNZ"
          },
          href: "https://api.spotify.com/v1/albums/7xl50xr9NDkd3i2kBbzsNZ",
          id: "7xl50xr9NDkd3i2kBbzsNZ",
          images: [
            {
              height: 568,
              url: "https://i.scdn.co/image/fd62b1f4f697284a024784706949bff3a6e1a27e",
              width: 640
            },
            {
              height: 266,
              url: "https://i.scdn.co/image/49d5dd41404224772cecfff55233fbfeb4de8628",
              width: 300
            },
            {
              height: 57,
              url: "https://i.scdn.co/image/55b6dee8efb5e78dee6c6e81650ca8e27b6dccfd",
              width: 64
            }
          ],
          name: "Stadium Arcadium",
          release_date: "2006-05-09",
          release_date_precision: "day",
          total_tracks: 29,
          type: "album",
          uri: "spotify:album:7xl50xr9NDkd3i2kBbzsNZ"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/1jWKVgnHX8nwR551hQNx5K"
          },
          href: "https://api.spotify.com/v1/albums/1jWKVgnHX8nwR551hQNx5K",
          id: "1jWKVgnHX8nwR551hQNx5K",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/b14027718a46fb43d8c6d8c88092fba9f75d9d21",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/39577b5613c625bd98e53ba74963be0a98bdd857",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/0efaf4d918fa1de42dbe8cdca0a1763b418fcfdf",
              width: 64
            }
          ],
          name: "By The Way",
          release_date: "2002-07-09",
          release_date_precision: "day",
          total_tracks: 16,
          type: "album",
          uri: "spotify:album:1jWKVgnHX8nwR551hQNx5K"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/6deiaArbeoqp1xPEGdEKp1"
          },
          href: "https://api.spotify.com/v1/albums/6deiaArbeoqp1xPEGdEKp1",
          id: "6deiaArbeoqp1xPEGdEKp1",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/b14027718a46fb43d8c6d8c88092fba9f75d9d21",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/39577b5613c625bd98e53ba74963be0a98bdd857",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/0efaf4d918fa1de42dbe8cdca0a1763b418fcfdf",
              width: 64
            }
          ],
          name: "By The Way (Deluxe Version)",
          release_date: "2002-07-09",
          release_date_precision: "day",
          total_tracks: 18,
          type: "album",
          uri: "spotify:album:6deiaArbeoqp1xPEGdEKp1"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/0fLhefnjlIV3pGNF9Wo8CD"
          },
          href: "https://api.spotify.com/v1/albums/0fLhefnjlIV3pGNF9Wo8CD",
          id: "0fLhefnjlIV3pGNF9Wo8CD",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/260c7a6da14bb13a4cc9e75bf5b549fb87fa22a9",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/6f98acc4da4eb86ca2f9ebae5f8f173e59c5abef",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/2da4d0271d9e4b1f37fd6c195e671d77ed61ca8f",
              width: 64
            }
          ],
          name: "Californication",
          release_date: "1999-06-08",
          release_date_precision: "day",
          total_tracks: 15,
          type: "album",
          uri: "spotify:album:0fLhefnjlIV3pGNF9Wo8CD"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/2Y9IRtehByVkegoD7TcLfi"
          },
          href: "https://api.spotify.com/v1/albums/2Y9IRtehByVkegoD7TcLfi",
          id: "2Y9IRtehByVkegoD7TcLfi",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/260c7a6da14bb13a4cc9e75bf5b549fb87fa22a9",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/6f98acc4da4eb86ca2f9ebae5f8f173e59c5abef",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/2da4d0271d9e4b1f37fd6c195e671d77ed61ca8f",
              width: 64
            }
          ],
          name: "Californication (Deluxe Version)",
          release_date: "1999-06-08",
          release_date_precision: "day",
          total_tracks: 18,
          type: "album",
          uri: "spotify:album:2Y9IRtehByVkegoD7TcLfi"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/74cQBDmkkzRBntR064f0SD"
          },
          href: "https://api.spotify.com/v1/albums/74cQBDmkkzRBntR064f0SD",
          id: "74cQBDmkkzRBntR064f0SD",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/8be0af1cf1c77db65874606af8b7a50f85cfae69",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ffedf303ec44d93205cfe32e4c5ce6af21456740",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/7bebe3ae621faec0b18dd524ad2f22f627c65e41",
              width: 64
            }
          ],
          name: "One Hot Minute",
          release_date: "1995-09-12",
          release_date_precision: "day",
          total_tracks: 13,
          type: "album",
          uri: "spotify:album:74cQBDmkkzRBntR064f0SD"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/2rQ135imvelvp89D8eEZOi"
          },
          href: "https://api.spotify.com/v1/albums/2rQ135imvelvp89D8eEZOi",
          id: "2rQ135imvelvp89D8eEZOi",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/c21abf8489821a05c7cf7425a01b08cee1b501d8",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/2888c8e1deee04f86182d3d5f1a9b3dd2d88f5d5",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/54dbe9ffc85eccbe41d93b327806b860483c8bf6",
              width: 64
            }
          ],
          name: "One Hot Minute (Deluxe Version)",
          release_date: "1995-09-12",
          release_date_precision: "day",
          total_tracks: 16,
          type: "album",
          uri: "spotify:album:2rQ135imvelvp89D8eEZOi"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/30Perjew8HyGkdSmqguYyg"
          },
          href: "https://api.spotify.com/v1/albums/30Perjew8HyGkdSmqguYyg",
          id: "30Perjew8HyGkdSmqguYyg",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/5a6a1c6514398dc4004c6348a83d77694a3883d4",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/5ec4ff29311f065813234bdeee7c1364960f0c3e",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/0fe6b80fd539eb74825b58c3fa62db459fa76b68",
              width: 64
            }
          ],
          name: "Blood Sugar Sex Magik (Deluxe Version)",
          release_date: "1991-09-24",
          release_date_precision: "day",
          total_tracks: 19,
          type: "album",
          uri: "spotify:album:30Perjew8HyGkdSmqguYyg"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/1oOkcBu5bgkUzZTvKD1m8z"
          },
          href: "https://api.spotify.com/v1/albums/1oOkcBu5bgkUzZTvKD1m8z",
          id: "1oOkcBu5bgkUzZTvKD1m8z",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/5e553d65e84fde60e3293ce2138a52e5f5b3ec10",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/1d875c76f4bd87149670068f3987b3c460b4f10b",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/5aee5b7aca9d5ee63308e79dedeb6e52fb720e03",
              width: 64
            }
          ],
          name: "Mother's Milk",
          release_date: "1989-08-16",
          release_date_precision: "day",
          total_tracks: 19,
          type: "album",
          uri: "spotify:album:1oOkcBu5bgkUzZTvKD1m8z"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/3rHJQrfEcBeSaLPuLwKR6F"
          },
          href: "https://api.spotify.com/v1/albums/3rHJQrfEcBeSaLPuLwKR6F",
          id: "3rHJQrfEcBeSaLPuLwKR6F",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/d10dee89f572280b7a5b3b5086a4d492576f0c88",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/b2f1380da5bf2b457f16e559d4c35dfec39e01fb",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/08bbd9b1965e8076ac7db283778df97eed494da2",
              width: 64
            }
          ],
          name: "The Uplift Mofo Party Plan",
          release_date: "1987",
          release_date_precision: "year",
          total_tracks: 12,
          type: "album",
          uri: "spotify:album:3rHJQrfEcBeSaLPuLwKR6F"
        },
        {
          album_group: "album",
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
              },
              href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
              id: "0L8ExT028jH3ddEcZwqJJ5",
              name: "Red Hot Chili Peppers",
              type: "artist",
              uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
            }
          ],
          available_markets: [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/10Oqhoq2akSJnurJOPk8xT"
          },
          href: "https://api.spotify.com/v1/albums/10Oqhoq2akSJnurJOPk8xT",
          id: "10Oqhoq2akSJnurJOPk8xT",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/70eedbb4441396ba0aeb016379b8addf74761437",
              width: 640
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/501de1d6d2fa63bb24a498787d37d847dbd71121",
              width: 300
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/a522aaf480ce2b32a75c8ae04be1bf803f09bb6a",
              width: 64
            }
          ],
          name: "Freaky Styley",
          release_date: "1985-08-16",
          release_date_precision: "day",
          total_tracks: 18,
          type: "album",
          uri: "spotify:album:10Oqhoq2akSJnurJOPk8xT"
        }
      ],
      "limit": 20,
      "next": "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5/albums?offset=20&limit=20&include_groups=album,single,compilation,appears_on",
      "offset": 0,
      "previous": null,
      "total": 45
    }
  ]);
}

module.exports = {
  getAlbums
};